#!/usr/bin/env ruby
# frozen_string_literal: true

require "ko"

class MyApplication < KO::Application
end

class MyObject < KO::Object
  signal :something

  # def on_ready
  #   pp("Ready #{id}")
  # end
end

MyApplication[] do
  x = MyObject["first"] do
    signal :blah

    MyObject["second"]

    on_ready do
      pp("Ready #{id}")
    end
  end
  t = MyObject["third"]
  t.parent = x
end

pp MyApplication.instance
