#!/usr/bin/env ruby
# frozen_string_literal: true

require "ko"

class MyApplication < KO::Application
end

class MyObject < KO::Object
  signal :something

  # def on_ready
  #   pp("Ready #{id}")
  # end
end

KO::Application[] do
  KO::Object["1"] do
    on_ready do
      pp("Ready #{id}")
    end

    KO::Object["11"] do
      on_ready do
        pp("Ready #{id}")
      end
    end
  end

  KO::Object["2"] do
    on_ready do
      pp("Ready #{id}")
    end

    KO::Object["22"] do
      on_ready do
        pp("Ready #{id}")
      end
    end
  end
end

pp MyApplication.instance
